### ISSUE TITLE
Finalizing CVPixelBuffer 0x17452bfe0 while lock count is 1.

### ISSUE THREAD

**Issue by BFMarks** [mortenjust/trainer-mac#4]
Hey Morten,

I re-trained the model with a very large data set size and now it's stuck on the error `Finalizing CVPixelBuffer 0x17452bfe0 while lock count is 1.`

Is that a problem with the trainer or tensorflow-swift?

Maybe it's related to this: http://stackoverflow.com/questions/35956538/how-to-read-qr-code-from-static-image/35957461

Could be a "spam-log" but the model doesn't really work now.

**Comment by mortenjust** [comment]
I think you may be right that it's a spam log entry. How does it behave differently that you expected? Just doesn't spit any results out at all? Any crashes?

**Comment by BFMarks** [comment]
Ok - I think the model is just much more complex so it's not able to obtain as high of certainty percentage.  Closing this issue for now.
